const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const Database = require('better-sqlite3');

const PORT = Number(process.env.PORT || 3000);
const ROOT = __dirname;
const db = new Database(path.join(ROOT, 'tiffinservice.sqlite'));
db.pragma('journal_mode = WAL');
db.exec(`
  CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
  CREATE TABLE IF NOT EXISTS customers (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, phone TEXT NOT NULL UNIQUE, address TEXT NOT NULL, plan_price INTEGER NOT NULL CHECK (plan_price > 0), joined_on TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
  CREATE TABLE IF NOT EXISTS pause_periods (id INTEGER PRIMARY KEY AUTOINCREMENT, customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE, start_date TEXT NOT NULL, end_date TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
  CREATE TABLE IF NOT EXISTS notification_outbox (id INTEGER PRIMARY KEY AUTOINCREMENT, customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE, delivery_date TEXT NOT NULL, channel TEXT NOT NULL DEFAULT 'sms', message TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(customer_id, delivery_date));
  CREATE TABLE IF NOT EXISTS subscription_transfers (id INTEGER PRIMARY KEY AUTOINCREMENT, from_customer_id INTEGER NOT NULL REFERENCES customers(id), to_customer_id INTEGER NOT NULL REFERENCES customers(id), transfer_date TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
  CREATE TABLE IF NOT EXISTS import_audit (id INTEGER PRIMARY KEY AUTOINCREMENT, phone TEXT, status TEXT NOT NULL, reason TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
  CREATE INDEX IF NOT EXISTS idx_customers_phone ON customers(phone);
  CREATE INDEX IF NOT EXISTS idx_pauses_customer ON pause_periods(customer_id);
  CREATE INDEX IF NOT EXISTS idx_outbox_date ON notification_outbox(delivery_date);
  CREATE INDEX IF NOT EXISTS idx_transfers_source ON subscription_transfers(from_customer_id);
`);

const sessions = new Map();
const PUBLIC = path.join(ROOT, 'public');
const json = (res, status, payload) => { res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8' }); res.end(JSON.stringify(payload)); };
const parseBody = (req) => new Promise((resolve, reject) => { let body = ''; req.on('data', (chunk) => { body += chunk; if (body.length > 1e6) reject(new Error('Payload too large')); }); req.on('end', () => { try { resolve(body ? JSON.parse(body) : {}); } catch { reject(new Error('Invalid JSON')); } }); req.on('error', reject); });
const hash = (password) => crypto.createHash('sha256').update(password).digest('hex');
const token = () => crypto.randomBytes(24).toString('hex');
const cookies = (req) => Object.fromEntries((req.headers.cookie || '').split(';').filter(Boolean).map((value) => { const [key, ...rest] = value.trim().split('='); return [key, rest.join('=')]; }));
const userFor = (req) => sessions.get(cookies(req).tiffinservice_session);
const requireUser = (req, res) => { const user = userFor(req); if (!user) { json(res, 401, { error: 'Please sign in to continue.' }); return null; } return user; };
const dateValue = (value) => /^\d{4}-\d{2}-\d{2}$/.test(value || '') ? value : null;
const weekdaysInMonth = (month) => { const [year, monthNumber] = month.split('-').map(Number); const total = new Date(Date.UTC(year, monthNumber, 0)).getUTCDate(); let weekdays = 0; for (let day = 1; day <= total; day += 1) { const weekday = new Date(Date.UTC(year, monthNumber - 1, day)).getUTCDay(); if (weekday > 0 && weekday < 6) weekdays += 1; } return weekdays; };
const isPaused = (customerId, day) => db.prepare('SELECT 1 FROM pause_periods WHERE customer_id = ? AND start_date <= ? AND (end_date IS NULL OR end_date >= ?)').get(customerId, day, day);
const customerWithStatus = (customer) => ({ ...customer, status: isPaused(customer.id, new Date().toISOString().slice(0, 10)) ? 'paused' : 'active' });
const customerFromBody = (body) => { const name = String(body.name || '').trim(); const phone = String(body.phone || '').trim(); const address = String(body.address || '').trim(); const planPrice = Math.round(Number(body.planPrice)); const joinedOn = dateValue(body.joinedOn) || new Date().toISOString().slice(0, 10); if (!name || !phone || !address || !Number.isFinite(planPrice) || planPrice < 1) throw new Error('Name, phone, address, and a valid plan price are required.'); return { name, phone, address, planPrice, joinedOn }; };
const normalizeDate = (value) => { const raw = String(value || '').trim(); if (dateValue(raw)) return raw; const match = raw.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/); if (match) { const [, first, second, year] = match; const day = Number(first) > 12 ? first : second; const month = Number(first) > 12 ? second : first; const normalized = `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`; return dateValue(normalized) ? normalized : null; } const parsed = new Date(raw); return Number.isNaN(parsed.valueOf()) ? null : parsed.toISOString().slice(0, 10); };
const weekdaysBetween = (start, end) => { let count = 0; for (let cursor = new Date(`${start}T00:00:00Z`); cursor <= new Date(`${end}T00:00:00Z`); cursor.setUTCDate(cursor.getUTCDate() + 1)) { if (cursor.getUTCDay() > 0 && cursor.getUTCDay() < 6) count += 1; } return count; };
const clockDate = (body) => normalizeDate(body.date) || new Date().toISOString().slice(0, 10);
const importRows = (body) => { if (Array.isArray(body.rows)) return body.rows; const csv = String(body.csv || '').trim(); if (!csv) return []; const lines = csv.split(/\r?\n/).filter(Boolean); const headers = lines.shift().split(',').map((header) => header.trim().toLowerCase().replace(/\s+/g, '_')); return lines.map((line) => { const values = line.split(',').map((value) => value.trim()); return Object.fromEntries(headers.map((header, index) => [header, values[index] || ''])); }); };

function handleApi(req, res, url) {
  if (req.method === 'POST' && url.pathname === '/api/auth/register') return parseBody(req).then((body) => { const name = String(body.name || '').trim(); const email = String(body.email || '').trim().toLowerCase(); const password = String(body.password || ''); if (!name || !email || password.length < 6) return json(res, 400, { error: 'Name, email, and a password of 6+ characters are required.' }); try { const result = db.prepare('INSERT INTO users (name, email, password_hash) VALUES (?, ?, ?)').run(name, email, hash(password)); const session = token(); sessions.set(session, { id: result.lastInsertRowid, name, email }); res.setHeader('Set-Cookie', `tiffinservice_session=${session}; HttpOnly; Path=/; SameSite=Lax`); return json(res, 201, { user: { name, email } }); } catch { return json(res, 409, { error: 'That email is already registered.' }); } });
  if (req.method === 'POST' && url.pathname === '/api/auth/login') return parseBody(req).then((body) => { const email = String(body.email || '').trim().toLowerCase(); const user = db.prepare('SELECT * FROM users WHERE email = ? AND password_hash = ?').get(email, hash(String(body.password || ''))); if (!user) return json(res, 401, { error: 'Email or password is incorrect.' }); const session = token(); sessions.set(session, { id: user.id, name: user.name, email: user.email }); res.setHeader('Set-Cookie', `tiffinservice_session=${session}; HttpOnly; Path=/; SameSite=Lax`); return json(res, 200, { user: { name: user.name, email: user.email } }); });
  if (req.method === 'POST' && url.pathname === '/api/auth/logout') { sessions.delete(cookies(req).tiffinservice_session); res.setHeader('Set-Cookie', 'tiffinservice_session=; Max-Age=0; Path=/'); return json(res, 200, { ok: true }); }
  if (req.method === 'GET' && url.pathname === '/api/auth/me') { const user = userFor(req); return user ? json(res, 200, { user }) : json(res, 401, { error: 'Not signed in.' }); }
  if (!requireUser(req, res)) return;
  if (req.method === 'POST' && url.pathname === '/clock') return parseBody(req).then((body) => { const date = clockDate(body); const weekday = new Date(`${date}T00:00:00Z`).getUTCDay(); if (weekday === 0 || weekday === 6) return json(res, 200, { date, created: 0, message: 'No weekday deliveries are due.' }); const customers = db.prepare('SELECT * FROM customers WHERE joined_on <= ?').all(date).filter((customer) => !isPaused(customer.id, date)); const insert = db.prepare('INSERT OR IGNORE INTO notification_outbox (customer_id, delivery_date, message) VALUES (?, ?, ?)'); const transaction = db.transaction(() => customers.map((customer) => insert.run(customer.id, date, `Your Tiffin Service lunch is scheduled for ${date}.`))); const results = transaction(); return json(res, 201, { date, created: results.reduce((total, result) => total + result.changes, 0), due: customers.length }); });
  if (req.method === 'GET' && url.pathname === '/outbox') { const date = url.searchParams.get('date'); const rows = db.prepare(`SELECT notification_outbox.*, customers.name, customers.phone FROM notification_outbox JOIN customers ON customers.id = notification_outbox.customer_id ${date ? 'WHERE delivery_date = ?' : ''} ORDER BY notification_outbox.id DESC`).all(...(date ? [date] : [])); return json(res, 200, { outbox: rows }); }
  if (req.method === 'POST' && url.pathname === '/api/customers/import') return parseBody(req).then((body) => { const report = { imported: 0, deduped: 0, rejected: 0, errors: [] }; const seen = new Set(); const insert = db.prepare('INSERT INTO customers (name, phone, address, plan_price, joined_on) VALUES (?, ?, ?, ?, ?)'); for (const [index, row] of importRows(body).entries()) { const name = String(row.name || row.customer_name || '').trim(); const phone = String(row.phone || row.mobile || '').replace(/\s+/g, '').trim(); const address = String(row.address || row.delivery_address || '').trim(); const planPrice = Math.round(Number(row.plan_price || row.planPrice || row.price)); const joinedOn = normalizeDate(row.joined_on || row.joinedOn || row.start_date); if (!phone || seen.has(phone) || db.prepare('SELECT 1 FROM customers WHERE phone = ?').get(phone)) { report.deduped += 1; if (!phone) { report.deduped -= 1; report.rejected += 1; report.errors.push(`Row ${index + 2}: phone is blank.`); } else seen.add(phone); continue; } seen.add(phone); if (!name || !address || !Number.isFinite(planPrice) || planPrice < 1 || !joinedOn) { report.rejected += 1; report.errors.push(`Row ${index + 2}: missing name, address, valid plan price, or date.`); continue; } try { insert.run(name, phone, address, planPrice, joinedOn); report.imported += 1; } catch { report.rejected += 1; report.errors.push(`Row ${index + 2}: could not be saved.`); } } return json(res, 201, report); });
  if (req.method === 'GET' && url.pathname === '/api/customers') { const search = `%${String(url.searchParams.get('search') || '').trim()}%`; const sort = ['name', 'plan_price', 'joined_on'].includes(url.searchParams.get('sort')) ? url.searchParams.get('sort') : 'created_at'; const order = url.searchParams.get('order') === 'asc' ? 'ASC' : 'DESC'; const page = Math.max(1, Number(url.searchParams.get('page') || 1)); const limit = Math.min(50, Math.max(1, Number(url.searchParams.get('limit') || 8))); const total = db.prepare('SELECT COUNT(*) AS count FROM customers WHERE name LIKE ? OR phone LIKE ?').get(search, search).count; const rows = db.prepare(`SELECT * FROM customers WHERE name LIKE ? OR phone LIKE ? ORDER BY ${sort} ${order} LIMIT ? OFFSET ?`).all(search, search, limit, (page - 1) * limit).map(customerWithStatus); return json(res, 200, { customers: rows, total, page, pages: Math.ceil(total / limit) }); }
  if (req.method === 'POST' && url.pathname === '/api/customers') return parseBody(req).then((body) => { try { const customer = customerFromBody(body); const result = db.prepare('INSERT INTO customers (name, phone, address, plan_price, joined_on) VALUES (?, ?, ?, ?, ?)').run(customer.name, customer.phone, customer.address, customer.planPrice, customer.joinedOn); return json(res, 201, { customer: customerWithStatus(db.prepare('SELECT * FROM customers WHERE id = ?').get(result.lastInsertRowid)) }); } catch (error) { return json(res, 400, { error: error.message.includes('UNIQUE') ? 'A customer with that phone already exists.' : error.message }); } });
  const customerMatch = url.pathname.match(/^\/api\/customers\/(\d+)$/); const pauseMatch = url.pathname.match(/^\/api\/customers\/(\d+)\/pause$/); const billMatch = url.pathname.match(/^\/api\/customers\/(\d+)\/bill$/); const transferMatch = url.pathname.match(/^\/api\/customers\/(\d+)\/transfer$/);
  if (customerMatch && req.method === 'GET') { const customer = db.prepare('SELECT * FROM customers WHERE id = ?').get(customerMatch[1]); return customer ? json(res, 200, { customer: customerWithStatus(customer), pauses: db.prepare('SELECT * FROM pause_periods WHERE customer_id = ? ORDER BY start_date DESC').all(customer.id) }) : json(res, 404, { error: 'Customer not found.' }); }
  if (pauseMatch && req.method === 'POST') return parseBody(req).then((body) => { const customer = db.prepare('SELECT * FROM customers WHERE id = ?').get(pauseMatch[1]); const startDate = dateValue(body.startDate); if (!customer || !startDate) return json(res, 400, { error: 'Customer and pause start date are required.' }); const endDate = body.endDate ? dateValue(body.endDate) : null; if (body.endDate && !endDate) return json(res, 400, { error: 'Pause end date is invalid.' }); db.prepare('INSERT INTO pause_periods (customer_id, start_date, end_date) VALUES (?, ?, ?)').run(customer.id, startDate, endDate); return json(res, 201, { customer: customerWithStatus(customer) }); });
  if (pauseMatch && req.method === 'DELETE') { const yesterday = new Date(Date.now() - 86400000).toISOString().slice(0, 10); db.prepare('UPDATE pause_periods SET end_date = COALESCE(end_date, ?) WHERE customer_id = ? AND end_date IS NULL').run(yesterday, pauseMatch[1]); return json(res, 200, { ok: true }); }
  if (transferMatch && req.method === 'POST') return parseBody(req).then((body) => { const from = db.prepare('SELECT * FROM customers WHERE id = ?').get(transferMatch[1]); const transferDate = normalizeDate(body.transferDate); if (!from || !transferDate || transferDate < from.joined_on) return json(res, 400, { error: 'A valid transfer date on or after the subscription start is required.' }); try { const to = customerFromBody({ ...body, planPrice: from.plan_price, joinedOn: transferDate }); const result = db.prepare('INSERT INTO customers (name, phone, address, plan_price, joined_on) VALUES (?, ?, ?, ?, ?)').run(to.name, to.phone, to.address, to.planPrice, to.joinedOn); db.prepare('INSERT INTO subscription_transfers (from_customer_id, to_customer_id, transfer_date) VALUES (?, ?, ?)').run(from.id, result.lastInsertRowid, transferDate); return json(res, 201, { from: customerWithStatus(from), to: customerWithStatus(db.prepare('SELECT * FROM customers WHERE id = ?').get(result.lastInsertRowid)), transferDate }); } catch (error) { return json(res, 400, { error: error.message.includes('UNIQUE') ? 'The new customer phone already exists.' : error.message }); } });
  if (billMatch && req.method === 'GET') { const customer = db.prepare('SELECT * FROM customers WHERE id = ?').get(billMatch[1]); const month = /^\d{4}-\d{2}$/.test(url.searchParams.get('month') || '') ? url.searchParams.get('month') : new Date().toISOString().slice(0, 7); if (!customer) return json(res, 404, { error: 'Customer not found.' }); const totalWeekdays = weekdaysInMonth(month); const pauses = db.prepare('SELECT * FROM pause_periods WHERE customer_id = ? AND start_date < ? AND (end_date IS NULL OR end_date >= ?)').all(customer.id, `${month}-32`, `${month}-01`); const outgoing = db.prepare('SELECT * FROM subscription_transfers WHERE from_customer_id = ? ORDER BY transfer_date LIMIT 1').get(customer.id); const incoming = db.prepare('SELECT * FROM subscription_transfers WHERE to_customer_id = ? ORDER BY transfer_date DESC LIMIT 1').get(customer.id); let pausedWeekdays = 0; for (let day = 1; day <= 31; day += 1) { const date = `${month}-${String(day).padStart(2, '0')}`; const parsed = new Date(`${date}T00:00:00Z`); if (parsed.getUTCMonth() + 1 !== Number(month.slice(5))) continue; const weekday = parsed.getUTCDay(); const outsideCycle = (incoming && date < incoming.transfer_date) || (outgoing && date >= outgoing.transfer_date); if (weekday > 0 && weekday < 6 && (outsideCycle || pauses.some((pause) => pause.start_date <= date && (!pause.end_date || pause.end_date >= date)))) pausedWeekdays += 1; } const servedDays = Math.max(0, totalWeekdays - pausedWeekdays); return json(res, 200, { bill: { month, planPrice: customer.plan_price, totalWeekdays, pausedWeekdays, servedDays, amount: Math.round(customer.plan_price * servedDays / totalWeekdays), transfer: outgoing ? { direction: 'out', date: outgoing.transfer_date, successorId: outgoing.to_customer_id } : incoming ? { direction: 'in', date: incoming.transfer_date, predecessorId: incoming.from_customer_id } : null } }); }
  return json(res, 404, { error: 'API route not found.' });
}

const server = http.createServer((req, res) => { const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`); if (url.pathname.startsWith('/api/') || url.pathname === '/clock' || url.pathname === '/outbox') return Promise.resolve().then(() => handleApi(req, res, url)).catch((error) => json(res, 500, { error: error.message })); const requested = url.pathname === '/' ? '/index.html' : url.pathname; const file = path.join(PUBLIC, requested); if (!file.startsWith(PUBLIC)) return json(res, 404, { error: 'Not found.' }); fs.readFile(file, (error, content) => { if (error) return json(res, 404, { error: 'Not found.' }); const types = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css' }; res.writeHead(200, { 'Content-Type': `${types[path.extname(file)] || 'text/plain'}; charset=utf-8` }); res.end(content); }); });
server.listen(PORT, () => console.log(`Tiffin Service is running at http://localhost:${PORT}`));